name: webrtc_interface
description: WebRTC Interface for Dart-Web/Flutter.
version: 1.0.5
homepage: https://flutter-webrtc.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  import_sorter: ^4.6.0
  pedantic: ^1.11.1
  test: any
